### ISSUE TITLE
om m1 mac issues with hypervisor not detecting it

### ISSUE THREAD

**Issue by pedrouga** [Dewalt-arch/pimpmykali#15] opened 2022-06-25 19:08 UTC
[++] detecting hypervisor type 

grep: /proc/device-tree/compatible: No such file or directory
grep: /proc/device-tree/compatible: No such file or directory
grep: /proc/device-tree/compatible: No such file or directory

 [**] Hypervisor not detected, Possible bare-metal installation not updating

**Comment by Dewalt-arch** [comment] 2022-06-26 14:13
Pimpmykali was never designed nor intended to be run on an M1 Mac
Nevermind the M1 did not even exist when PMK was created... 

The function your speaking of is using virt-what to determine the hypervisor. 

PMK is working as intended... closing ticket

**Closed by Dewalt-arch** 2022-06-26 14:13 UTC
