### ISSUE TITLE
gedit(root) conn refused fix not working

### ISSUE THREAD

**Issue by muazazhar** [Dewalt-arch/pimpmykali#8] opened 2022-01-20 14:04 UTC
![image](https://user-images.githubusercontent.com/49091541/150353633-10c80aa2-fa40-4a85-898d-5c3192e6fdc0.png)

**Comment by Dewalt-arch** [comment] 2022-01-20 14:17
If you are using sudo su -    to get to root, stop using the - 
ie: dont use "sudo su - "   use just sudo su

The - provides an environment 'like' root, but it is not actually 'root'

Non pimpmykali related issue, 1.4.1 was tested, and is working as intended. 
-- Closing issue

**Closed by Dewalt-arch** 2022-01-20 14:17 UTC
